feature_store:
  bucket_name: featurestorek10
  file_name: HeartDiseaseTrain-Test.csv

model_registry:
  bucket_name: modelregistryk10
  test_folder: testing
  prod_folder: production
  package_name : artifacts
  zip_files:
    - model.pkl
    - encoder.pkl
    - scaler.pkl

email_params:
  sender_email: dtu.gourav@gmail.com
  receiver_email: dtu.gourav@gmail.com
  application_key:
  train_message : "Model Trained and successfully Registered"
  test_message : "Model Test and successfully shifted into Production"
  endpoint_message: "Endpoint updated"


ml_params:
  test_size: 0.33
  random_state: 101
  label: target






